steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/ourplaces-dev-pav/ourplaces-dev-pav-image:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/ourplaces-dev-pav/ourplaces-dev-pav-image:$SHORT_SHA']
